export const EMPLOYEE_LIST_REQUEST = "EMPLOYEE_LIST_REQUEST";
export const EMPLOYEE_LIST_SUCCESS = "EMPLOYEE_LIST_SUCCESS";
export const EMPLOYEE_LIST_FAIL = "EMPLOYEE_LIST_FAIL";
export const EMPLOYEE_LIST_RESET = "EMPLOYEE_LIST_RESET";

export const EMPLOYEE_ADD_SINGLE_REQUEST = "EMPLOYEE_ADD_SINGLE_REQUEST";
export const EMPLOYEE_ADD_SINGLE_SUCCESS = "EMPLOYEE_ADD_SINGLE_SUCCESS";
export const EMPLOYEE_ADD_SINGLE_FAIL = "EMPLOYEE_ADD_SINGLE_FAIL";
export const EMPLOYEE_ADD_SINGLE_RESET = "EMPLOYEE_ADD_SINGLE_RESET";

export const EMPLOYEE_ADD_MULTI_REQUEST = "EMPLOYEE_ADD_MULTI_REQUEST";
export const EMPLOYEE_ADD_MULTI_SUCCESS = "EMPLOYEE_ADD_MULTI_SUCCESS";
export const EMPLOYEE_ADD_MULTI_FAIL = "EMPLOYEE_ADD_MULTI_FAIL";
export const EMPLOYEE_ADD_MULTI_RESET = "EMPLOYEE_ADD_MULTI_RESET";
